Ativa template inspecting para ver detalhes de pacote
scieloorg/scms-upload pull request #25
Opened 2022-08-02 17:55 UTC by rafaelpezzuto

#### O que esse PR faz?
Este PR ativa o template InspectView e extende seu template para exibir links e botões extras.

Outra parte do PR simplifica o código-fonte existente (remove permissões, botões e regras desnecessárias e que podem atrapalhar o andamento do projeto). A ideia de remover esse pedaço do código-fonte é não enviesar futuros desenvolvimentos.

#### Onde a revisão poderia começar?
Por commits.

#### Como este poderia ser testado manualmente?
Execute:
```bash
make build
make up
make django_makemigrations
make django_migrate
make django_createsuperuser
```
- Crie um grupo "Depositor"
- Adiciona a esse grupo as permissões: (a) package: add, view, finish_deposit e (b) can access wagtail admin.
- Crie um usuário qualquer e o adicione ao grupo "Depositor"
- Envie pacotes zip
- Liste pacotes
- Clique em `Inspecionar` para ver dados do pacote enviado

#### Algum cenário de contexto que queira dar?
N/A

### Screenshots
![image](https://user-images.githubusercontent.com/2096125/182441695-d0b85ee2-94a3-43c0-9b12-990a40e6f446.png)

![image](https://user-images.githubusercontent.com/2096125/182441815-ebfa8bac-efe5-4ac2-87ba-5744ae5678b7.png)

#### Quais são tickets relevantes?
#10 

### Referências
N/A

2022-08-02 18:20 UTC, rafaelpezzuto commented
@gitnnolabs Faz alguma ideia de como lidar com aquele campo que lista os pacotes (`files list`), quero dizer, sabe se é possível adicionar uma personalização no inspect.html ou no wagtailhooks que melhora a visualização daquele campo (`files list`).

2022-08-03 12:38 UTC, robertatakenaka commented on upload/views.py
> +        package.status = PackageStatus.FINISHED
@rafaelpezzuto podemos considerar que ele somente pode habilitar o `finish_deposit` se o status atual é `VALIDATED_WITHOUT_ERRORS`. (A funcionalidade do botão será outro issue que descreverá que haverá um campo de justificativa ou de ciência de que isso não garante o ACEITE)
É provável que por questão de automação, podemos considerar que `VALIDATED_WITHOUT_ERRORS` poderia levar a diretamente `ACCEPTED` (abrirei issue para isso)

2022-08-03 12:40 UTC, robertatakenaka commented on upload/button_helper.py
> +        if obj.status != int(PackageStatus.FINISHED) and ph.user_can_finish_deposit(usr, obj):
@rafaelpezzuto comparar com status `VALIDATED_WITH_ERRORS` no lugar de != FINISHED

2022-08-03 12:51 UTC, robertatakenaka requested changes
@rafaelpezzuto Na lista deixar somente **inspect**, todas as ações devem partir da página de detalhes, principalmente porque acredito que nenhuma ação que qq usuário vá fazer, terão informação suficiente pelo conteúdo da lista. Também verificar os demais comentários.

2022-08-03 12:51 UTC, robertatakenaka commented on upload/templates/modeladmin/upload/package/detail.html
> +        <!-- Por exemplo, pode ser condicionado a um campo is_published (package.is_published == True) -->
@rafaelpezzuto  no lugar de `package.is_published == True` na verdade é `status == PUBLISHED`

2022-08-03 13:24 UTC, gitnnolabs commented
> @gitnnolabs Faz alguma ideia de como lidar com aquele campo que lista os pacotes (`files list`), quero dizer, sabe se é possível adicionar uma personalização no inspect.html ou no wagtailhooks que melhora a visualização daquele campo (`files list`).

@rafaelpezzuto acredito que seja alguma re-escrita em **block** do template: '/templates/modeladmin/app-name/model-name/inspect.html'

Acredito que essa documentação pode te ajudar: https://docs.wagtail.org/en/stable/reference/contrib/modeladmin/primer.html#modeladmin-overriding-templates

2022-08-03 13:29 UTC, rafaelpezzuto commented
> > @gitnnolabs Faz alguma ideia de como lidar com aquele campo que lista os pacotes (`files list`), quero dizer, sabe se é possível adicionar uma personalização no inspect.html ou no wagtailhooks que melhora a visualização daquele campo (`files list`).
> 
> @rafaelpezzuto acredito que seja alguma re-escrita em **block** do template: '/templates/modeladmin/app-name/model-name/inspect.html'
> 
> Acredito que essa documentação pode te ajudar: https://docs.wagtail.org/en/stable/reference/contrib/modeladmin/primer.html#modeladmin-overriding-templates

Ah sim, eu já tinha visto essa doc. De qualquer forma, olhando o template original percebe que basta reescrever o trecho o block `{% block fields_output %}`. Farei isso.

2022-08-03 14:20 UTC, rafaelpezzuto commented on upload/button_helper.py
> +        if obj.status != int(PackageStatus.FINISHED) and ph.user_can_finish_deposit(usr, obj):
@robertatakenaka O correto é `VALIDATED_WITHOUT_ERRORS`.

2022-08-03 15:47 UTC, rafaelpezzuto commented
@robertatakenaka O wagtail tem todo um jeito de colocar botões nos lugares. Cheguei num ponto aqui que considero bom para fazer com que o "finish" seja exibido na tela de detalhes e o "ver documento, se publicado" funcione bem tbm. 

Tela de detalhes de pacote com um menu "ações" na parte inferior - é um menu padrão do wagtail (via button_helper) que é melhor para controlar o que pode ou não pode ser exibido.
![image](https://user-images.githubusercontent.com/2096125/182651064-c2b7fbf8-b582-4fed-a6b7-db5df24ae7e2.png)

Acho que se o documento está publicado, deve ser possível ver o botão "ver documento" na listagem de pacotes, o que acha?
![image](https://user-images.githubusercontent.com/2096125/182651303-d9c4ca63-f333-4d4e-907a-c9e3ebe9b680.png)

2022-08-03 17:03 UTC, robertatakenaka commented on upload/button_helper.py
> +        if obj.status != int(PackageStatus.FINISHED) and ph.user_can_finish_deposit(usr, obj):
@rafaelpezzuto seria com erros, pois sem erros, o sistema pode passar adiante automaticamente.
Com erros, exige que o depositante aceito o risco de ser rejeitado no controle de qualidade.

2022-08-03 17:21 UTC, robertatakenaka approved these changes

2022-08-03 19:00 UTC, merged