Adiciona o modelo de journal.
scieloorg/scms-upload pull request #38
Opened 2022-08-15 15:06 UTC by gitnnolabs

#### O que esse PR faz?

Adiciona o modelo de Journal com os seguinte campos: 

- id generado por el sistema
- official_title (Título do periódico conforme registro do ISSN)
- foundation_year (Ano de criação do periódico)
- ISSN Print
- ISSN Electronic
- ISSN SciELO
- ISSNL

#### Onde a revisão poderia começar?

Por commit.

#### Como este poderia ser testado manualmente?

Subindo uma instância local da aplicação e utilizando o modelo de Journal.

#### Algum cenário de contexto que queira dar?
N/A

### Screenshots

![Captura de Tela 2022-08-15 às 12 02 14](https://user-images.githubusercontent.com/86991526/184660700-ec3946ad-f9fe-4a92-b788-0a0210c69b34.png)
![Captura de Tela 2022-08-15 às 12 02 07](https://user-images.githubusercontent.com/86991526/184660714-7251b77e-fab6-4c0e-85da-183afcd5868e.png)

#### Quais são tickets relevantes?

https://github.com/scieloorg/scms-upload/issues/5

### Referências
M/A

2022-08-15 19:18 UTC, robertatakenaka commented on journal/migrations/0001_initial.py
> +            },
o que é abstract?

2022-08-15 19:29 UTC, robertatakenaka commented
@gitnnolabs Repensei o modelo que deve se chamar `OfficialJournal` para explicitar que é um registro especial. Sendo assim, fica desnecessário o campo `title` ter o prefixo `official`. Também deve ser removido o issn_scielo.

2022-08-17 01:43 UTC, rafaelpezzuto approved these changes
Fiquei com dúvidas em relação a não-obrigatoriedade dos campos ISSN (SciELO e ISSN-L). Mas em geral, parece tudo ótimo.

2022-08-17 01:43 UTC, rafaelpezzuto commented on journal/models.py
> +    ISSN_scielo = models.CharField(_('ISSN SciELO'), max_length=9, null=True, blank=True)
Não seria mais correto ter null=False?

2022-08-17 01:43 UTC, rafaelpezzuto commented on journal/models.py
> +    ISSNL = models.CharField(_('ISSNL'), max_length=9, null=True, blank=True)
Não seria mais correto ter null=False?

2022-08-17 13:02 UTC, rafaelpezzuto requested changes
Alterar de acordo com a nova modelagem indica pela Roberta.

2022-08-17 13:14 UTC, robertatakenaka commented
@gitnnolabs não tinha vista pela perspectiva de obrigatório e opcional. Eu sugiro deixar todos obrigatórios, exceto o print. Como os dados são provenientes de uma base de dados oficial, os campos existem. E seria estranho trabalhar com um periódico sem ISSN eletrônico, bem exceto se ele for antigo... Aí faria sentido estar como opcional. @rafaelpezzuto você acha que haverá casos de ISSN L ausente? Talvez para títulos antigos?

2022-08-25 18:06 UTC, closed without merging