Refatora Função no Módulo de Publicação de Journal para utilizar dados do modelo Journal
scieloorg/scms-upload pull request #444
Opened 2024-04-18 14:32 UTC by samuelveigarangel

#### O que esse PR faz?
Refatora Função no Módulo de Publicação de Journal para utilizar dados do modelo Journal

#### Onde a revisão poderia começar?
pelos commits

#### Como este poderia ser testado manualmente?

#### Algum cenário de contexto que queira dar?
N;A

### Screenshots
N;A

#### Quais são tickets relevantes?
#436 

### Referências
N/A

2024-05-06 16:52 UTC, robertatakenaka commented on journal/models.py
> +        f"{self.year}-{self.month}-{self.day}"
@samuelveigarangel falta return

2024-05-06 16:53 UTC, robertatakenaka commented on journal/models.py
> +        return f"{self.event_type} {self.interruption_reason} {self.year}/{self.month}/{self.day or '01'}"
@samuelveigarangel não adulterar o valor de day

2024-05-06 16:54 UTC, robertatakenaka commented on journal/models.py
> +    def am_to_core(
@samuelveigarangel renomear para um nome mais significativo

2024-05-06 16:54 UTC, robertatakenaka commented on journal/models.py
> +        Atualiza o Type Event de JournalHistory.
@samuelveigarangel a interação é core com upload. Não deveria ter envolvimento com AM

2024-05-06 16:56 UTC, robertatakenaka commented on proc/models.py
> -from issue.models import Issue
@samuelveigarangel qual é o motivo de substituir isso?

2024-05-06 16:57 UTC, robertatakenaka commented on proc/models.py
> -from journal.models import Journal
@samuelveigarangel qual é o motivo de excluir isso?

2024-05-06 16:57 UTC, robertatakenaka commented on proc/models.py
> +            Article = apps.get_model("article", "Article")
@samuelveigarangel qual é o motivo? Isso não deixa mais lento?

2024-05-06 16:58 UTC, robertatakenaka commented on publication/utils/journal.py
>  from scielo_classic_website.models.journal import Journal as ClassicJournal
@samuelveigarangel está usando ClassicJournal ainda?

2024-05-06 16:59 UTC, robertatakenaka commented on upload/models.py
> -from article.models import Article
@samuelveigarangel qual é o motivo de excluir Article, Issue e Journal?

2024-05-06 17:00 UTC, robertatakenaka requested changes
Verificar comentários

2024-05-08 14:17 UTC, samuelveigarangel commented on journal/models.py
> +    def am_to_core(
Acho que posso remove essa funcao.

2024-05-08 14:19 UTC, samuelveigarangel commented on journal/models.py
> +    def am_to_core(
Importe para popular os dados de Journal em Publication

2024-05-08 14:20 UTC, samuelveigarangel commented on proc/models.py
> -from journal.models import Journal
Estava com problemas de importacao circular

2024-05-08 14:24 UTC, samuelveigarangel commented on proc/models.py
> +            Article = apps.get_model("article", "Article")
Eu estava enfrentando problemas com importações circulares, achei  esta forma de importar um modelo para evitar.  Não tenho certeza sobre o custo associado a essa função, mas acredito que seja mínimo.Outra opção é importar o módulo diretamente dentro da função que deve produzir um resultado semelhante.

2024-05-08 17:27 UTC, robertatakenaka commented on journal/models.py
> +        except SubjectCreationOrUpdateError as e:
@samuelveigarangel aqui tem que ser Exception ou ValueError, pois SubjectCreationOrUpldateError nunca ocorrerá.

2024-05-08 17:28 UTC, robertatakenaka commented on proc/models.py
> +            Article = apps.get_model("article", "Article")
@samuelveigarangel entendi. Adiciona um comentário da motivação

2024-05-08 17:30 UTC, robertatakenaka requested changes
Verificar

2024-05-08 18:51 UTC, samuelveigarangel commented on journal/models.py
> +        except SubjectCreationOrUpdateError as e:
SubjectCreationOrUpdateError é uma classe que tem herança com Exception. Então toda exceção ira ser capturada.
```python
class SubjectCreationOrUpdateError(Exception):
    def __init__(self, code, message):
        super().__init__(
            f"Unable to create or update Subject with code: {code}: {str(message)}"
        )
```

2024-05-08 19:22 UTC, merged