Implementar verificação de disponibilidade de artigos em scielo.br
scieloorg/scms-upload pull request #462
Opened 2024-05-21 18:17 UTC by samuelveigarangel

#### O que esse PR faz?
Este PR implementa uma funcionalidade automatizada que verifica a disponibilidade dos artigos tanto na versão nova quanto na versão antiga do SciELO. Após a verificação, os resultados são armazenados em modelos específicos e disponibilizados na interface administrativa para consulta.

#### Onde a revisão poderia começar?
Pelos commit https://github.com/scieloorg/scms-upload/commit/b8901abaf9461316fce916a78e679acf24ae5e8a

#### Como este poderia ser testado manualmente?
1. make django_bash
```console
python manage.py runscript load_check_article --script-args {username} 
```
Obs: É importante registrar coleção e periódico e realizar relacionamento com um artigo.

#### Algum cenário de contexto que queira dar?
N/A

### Screenshots
![image](https://github.com/scieloorg/scms-upload/assets/82840278/432788a5-c161-400b-b215-d7006328c3bb)

#### Quais são tickets relevantes?
#454 

### Referências
N/A

2024-05-22 11:37 UTC, robertatakenaka commented on article/tasks.py
> +        f"https://www.scielo.br/j/{journal_acron}/a/{pid_v3}/?lang={lang}"
@samuelveigarangel a parte www.scielo.br deve ser obtida da class Collection, no entanto, acho que ela está bem diferente da que está no Core. Será necessário atualizá-la

2024-05-22 11:38 UTC, robertatakenaka commented on article/tasks.py
> +        f"https://www.scielo.br/j/{journal_acron}/a/{pid_v3}/?lang={lang}"
@samuelveigarangel adicionar também os formatos pdf

2024-05-22 11:38 UTC, robertatakenaka commented on article/tasks.py
> +        f"https://www.scielo.br/j/{journal_acron}/a/{pid_v3}/?lang={lang}"
@samuelveigarangel acho que seria interessante colocar como melhoria o tempo de resposta

2024-05-22 11:39 UTC, robertatakenaka commented on article/tasks.py
> +                    status=True,
@samuelveigarangel trocar True / False por HTTP ERROR CODE, ou pode ser um outro atributo

2024-05-22 11:48 UTC, robertatakenaka reviewed
@samuelveigarangel Muito bom!

2024-05-22 13:17 UTC, samuelveigarangel commented on article/tasks.py
> +        f"https://www.scielo.br/j/{journal_acron}/a/{pid_v3}/?lang={lang}"
@robertatakenaka Verdade. Acho que posso conseguir esse dado em: https://github.com/scieloorg/scms-upload/blob/91234dd4f0e521e74270df4a9b21c935071cdd0e/collection/models.py#L65

2024-06-26 11:17 UTC, robertatakenaka commented on article/tasks.py
> +                        domain=article.journal.journalproc_set.first().collection.websiteconfiguration_set.get(enabled=True).url,
@samuelveigarangel o teste tem que ser feito para todas as coleções registradas

2024-06-26 11:18 UTC, robertatakenaka commented on article/models.py
> +    article = models.ForeignKey(
@samuelveigarangel adicione a collection de modo que checará a disponibilidade em todas as coleções. Também deveria ser considerado a disponibilidade no site QA

2024-12-04 13:19 UTC, robertatakenaka commented on article/choices.py
> +VERIFY_ARTICLE_TYPE = [
@samuelveigarangel nome não adequado, melhor FORMAT no lugar de ARTICLE_TYPE

2024-12-04 13:19 UTC, robertatakenaka commented on article/models.py
> +def verify_type_of_url(type):
@samuelveigarangel qual é a necessidade desta função?

2024-12-04 13:21 UTC, robertatakenaka commented on article/models.py
> +class CheckArticleAvailability(CommonControlField):
@samuelveigarangel Use `ArticleAvailability` no lugar de `CheckArticleAvailability`

2024-12-04 13:22 UTC, robertatakenaka commented on article/models.py
> +class CheckArticleAvailability(CommonControlField):
@samuelveigarangel  mova este modelo para dentro de publication, pois dentro de publication podemos importar quaisquer outros modelos como JournalProc, IssueProc e outros minimizando problemas de dependências circulares

2024-12-04 13:23 UTC, robertatakenaka commented on article/models.py
> +        "ScieloSiteStatus"
@samuelveigarangel mude para url_status e "URLStatus

2024-12-04 13:24 UTC, robertatakenaka commented on article/models.py
> +    check_date = models.DateTimeField(null=True, blank=True)
@samuelveigarangel precisa de check_date se há updated?

2024-12-04 13:24 UTC, robertatakenaka commented on article/models.py
> +    url_site_scielo = models.SlugField(max_length=500, unique=True)
@samuelveigarangel por que SlugField no lugar de URLField?

2024-12-04 13:25 UTC, robertatakenaka commented on article/models.py
> +    status = models.CharField(
@samuelveigarangel use HTTPCode (SmallPositiveInteger)

2024-12-04 13:26 UTC, robertatakenaka commented on article/models.py
> +    type = models.CharField(
@samuelveigarangel precisa desta distinção?

2024-12-04 13:26 UTC, robertatakenaka commented on article/models.py
> +    available = models.BooleanField(default=False)
@samuelveigarangel qual é a diferença entre status e available?

2024-12-04 13:27 UTC, robertatakenaka commented on article/models.py
> +        verbose_name_plural = "Scielo Site Status"
URL status

2024-12-04 13:29 UTC, robertatakenaka commented on article/tasks.py
> +import re
@samuelveigarangel mover este conteúdo para publication/tasks.py

2024-12-04 13:29 UTC, robertatakenaka commented on article/wagtail_hooks.py
> +from .models import Article, RelatedItem, RequestArticleChange, choices, ScieloSiteStatus
@samuelveigarangel mover este conteúdo para publication/wagtail_hooks.py

2024-12-04 13:31 UTC, robertatakenaka requested changes
@samuelveigarangel separar em 2 PRs: refatoração do get_user e solução da verificação da disponibilidade do site

2024-12-08 23:40 UTC, samuelveigarangel commented
@robertatakenaka, vou fechar esta PR e abrir uma nova com o repositório atualizado, pois esta branch está bastante desatualizada.

2024-12-09 00:03 UTC, samuelveigarangel commented on article/models.py
> +    available = models.BooleanField(default=False)
Status pode dar uma mensagem melhor para o usuário. Distingué entre uma URL errada ou instabilidade na URL. Talvez o nome do campo possa ser melhor.

2024-12-09 00:12 UTC, samuelveigarangel commented on article/models.py
> +    check_date = models.DateTimeField(null=True, blank=True)
Sim, pelo fato de que pode haver o caso de verificar um site que ainda continua disponível. Nesse casos, não haveria mudanças nos campos.

2024-12-09 00:38 UTC, samuelveigarangel commented on article/models.py
> +def verify_type_of_url(type):
Não há necessidade de verificar a URL  do pdf do artigo?

2025-01-06 04:06 UTC, closed without merging