Cria a funcionalidade de migrar e publicar periódicos (draft)
scieloorg/scms-upload pull request #89
Opened 2022-09-26 01:23 UTC by robertatakenaka

#### O que esse PR faz?
Cria a funcionalidade de migrar e publicar periódicos

#### Onde a revisão poderia começar?
por commits, a partir de 38eb01e572af4179bd91d4b074c46220a6738dc4

#### Como este poderia ser testado manualmente?
Assegure-se de ter preenchidos as configurações: coleção, site clássico (use 
Acessar pelo menu a opção "Tasks" > "Periodic Tasks"
Adicionar uma task nova
Preencher nome
Preencher kwargs com `{"collection_acron": "scl", "user_id": 1}`
Preencher o campo crontab
Salvar
Na lista de tarefas, selecionar o botão RUN da tarefa que acabou de criar.

#### Algum cenário de contexto que queira dar?
Indique um contexto onde as modificações se fazem necessárias ou passe informações que contextualizam
o revisor a fim de facilitar o entendimento da funcionalidade.

### Screenshots
Quando aplicável e se fizer possível adicione screenshots que remetem a situação gráfica do problema que o pull request resolve.

#### Quais são tickets relevantes?
Indique uma issue ao qual o pull request faz relacionamento.

### Referências
Indique as referências utilizadas para a elaboração do pull request.

2022-09-27 03:51 UTC, rafaelpezzuto requested changes
1. Configuração de coleção está ok;
2. Configuração de site clássico está ok;
3. Configuração de filestorage está ok;
4. Configuração de site novo está ok;
5. Configuração de migração falhou pois faltou definir o base_form_class para o modelo `MigrationConfiguration` - aliás, nós estamos criando o forms.py quase que idêntico para um monte de modelo - o ideal seria isso já vir com o CommonControlField;
6. Ocorre erro (como você previu) ao tentar acessar a tela de tasks (ausência do módulo scielo_classic_website) - acredito que seja a falta de arquivos __init__.py. Precisa criá-los na raiz `https://github.com/scieloorg/scielo_migration/tree/main/scielo_classic_website` e também dentro de cada módulo (fiz isso num repo local e instalei via -e; funcionou);
7. Configuração de task foi efetuada com sucesso (após a correção aplicada descrita acima)
8. Não houve erro de migração
9. Três periódicos foram gerados na aba `Migration > Journal Migration`

2022-09-28 14:09 UTC, rafaelpezzuto approved these changes
Está bem. Fiquei com dúvida nos tipos de campo dos modelos criados (se devem ser CharField ou DateField ou IntegerField).

2022-09-28 14:09 UTC, rafaelpezzuto commented on journal/models.py
>      foundation_year = models.CharField(_('Foundation Year'), max_length=4, null=True, blank=True)
@robertatakenaka Dúvida: Não seria melhor foundation_year ser IntegerField?

2022-09-28 14:09 UTC, rafaelpezzuto commented on journal/models.py
> +    foundation_date = models.CharField(_('Foundation Date'), max_length=8, null=True, blank=True)
@robertatakenaka Dúvida: Não seria melhor ser DateField?

2022-09-28 14:09 UTC, rafaelpezzuto commented on migration/controller.py
> +            if journal.first_year and journal.first_year.isdigit():
@robertatakenaka Dúvida: `first_year` não deveria ser IntegerField?

2022-09-28 14:09 UTC, rafaelpezzuto commented on migration/controller.py
> +            if journal.first_year and journal.first_year.isdigit():
@robertatakenaka Sobre as dúvidas de tipo de campo, sei que o modelo que vem do arquivo ID será uma string, porém, já não seria melhor garantir nesta parte do controller que o que vai para o modelo migrado já é o formato esperado para os campos que eu apontei?

2022-09-28 14:16 UTC, robertatakenaka commented on migration/controller.py
> +            if journal.first_year and journal.first_year.isdigit():
@rafaelpezzuto é um dado que veio do isis, logo é string, mas sendo o modelo OfficialJournal, de fato, seria melhor adequar os tipos. Só não sei se fica Integer ou Date.

2022-09-28 14:17 UTC, robertatakenaka commented on migration/controller.py
> +            if journal.first_year and journal.first_year.isdigit():
@rafaelpezzuto de qq modo vou alterar no próximo PR.

2022-09-28 14:17 UTC, merged