Adiciona suporte ao envio de pacotes com conteúdo inédito
scieloorg/scms-upload pull request #90
Opened 2022-09-27 21:11 UTC by rafaelpezzuto

#### O que esse PR faz?
Cria os mecanismos necessários para suportar o envio de pacotes com conteúdo inédito.

#### Onde a revisão poderia começar?
Por commits.

#### Como este poderia ser testado manualmente?
<PARA DESCREVER>

#### Algum cenário de contexto que queira dar?
Está em rascunho pois estou finalizando a parte que busca docs no opac e porque estou fazendo implementações no packtools.

### Screenshots
N/A

#### Quais são tickets relevantes?
#53 

### Referências
N/A

2022-09-30 16:16 UTC, robertatakenaka commented on journal/controller.py
> +        data['issn'] = [journal.ISSN_print, journal.ISSN_electronic]
Melhor identificar cada tipo

2022-09-30 16:17 UTC, robertatakenaka commented on upload/models.py
> +    journal = models.ForeignKey(OfficialJournal, blank=True, null=True, on_delete=models.SET_NULL)
article não contém issue que aponta para journal?

2022-09-30 16:18 UTC, robertatakenaka commented on upload/models.py
> +    journal = models.ForeignKey(OfficialJournal, blank=True, null=True, on_delete=models.SET_NULL)
mas é verdade que teoricamente aop está conectado ao journal e não a issue

2022-09-30 16:27 UTC, robertatakenaka commented on upload/tasks.py
> +
@rafaelpezzuto idealmente `sps_validation_journal.are_article_and_journal_data_compatible` deve levantar as exceções específicas, com a mensagem de erro de acordo e com os dados daquilo que causou a exceção.
Então, em `e` já vem a mensagem de que você está colocando no `if`

2022-09-30 16:30 UTC, robertatakenaka commented on upload/tasks.py
> +    article_data = site_utils.get_article_data_for_comparison(xmltree)
melhor, fica mais transparente

2022-09-30 16:38 UTC, robertatakenaka commented on upload/utils/site_utils.py
> +from packtools.sps.models import (
@rafaelpezzuto acho que este módulo ou a função deveria ficar no módulo libs/dsm/publication. Assim centralizamos tudo o que é relacionado com a interface de site novo aí.

2022-09-30 16:39 UTC, robertatakenaka commented on journal/controller.py
> +        data['electronic_issn'] = journal.ISSN_electronic
@rafaelpezzuto isso!

2022-09-30 16:42 UTC, robertatakenaka commented on upload/models.py
> +        if self.category in [
@rafaelpezzuto você pode criar um dicionário em que as chaves são as categorias e os valores os nomes dos relatórios.

2022-09-30 17:09 UTC, robertatakenaka commented on upload/templates/modeladmin/upload/package/validation_report/individual_content.html
> +        {% include "wagtailadmin/shared/header_with_locale_selector.html" with title=report_title subtitle=report_subtitle icon='doc-full' %}
@rafaelpezzuto sei que existe função para não ter que cravar no código as url tanto nos módulos python como nos templates

2022-09-30 17:16 UTC, robertatakenaka requested changes
Por questão de desempenho, será necessário eleger todos os dados usar a busca na base de dados para verificar se o documento já existe. Sugiro usar os títulos (ou pelo menos o principal), e os sobrenomes de todos os autores e o periódico.
Ocorrendo a exceção DoesNotExiste, pode ser considerado inédito. É possível de ocorrer Multiple... dependendo da ausência dos autores (talvez possa haver casos de ausência) e de títulos não significativos em um mesmo periódico. Neste caso, pode-ser fazer uma nova consulta mais restritiva ou fazer comparação com os resultados obtidos. Uma alternativa complementar é apresentar ao usuário e dar-lhe a decisão da desambiguação.

2022-10-04 18:14 UTC, rafaelpezzuto commented on upload/models.py
> +    journal = models.ForeignKey(OfficialJournal, blank=True, null=True, on_delete=models.SET_NULL)
@robertatakenaka, 

E se tivermos um issue para representar artigos que são `aop`? Assim manteríamos a consistência (troco `journal` por `issue`. Nessa situação teríamos um issue vinculado a um journal, porém, nesse issue não existiria volume, número, etc.

Quando um `aop` é transformado em `ex-aop`, bastaria trocar o `issue` genérico para o `final`.

2022-10-04 18:20 UTC, rafaelpezzuto commented on upload/tasks.py
> +
@robertatakenaka, no packtools sps_exceptions.ArticleIncompatibleDataError é um erro genérico herdado por ArticleHasIncompatibleJournalISSNError, sps_exceptions.ArticleHasIncompatibleJournalTitleError, ...). 

Para fazer apenas um `try/except`, optei por capturar a exceção pai e depois detectar qual das exceções filhas ocorreu. O termo `e` contém os dados do erro, de fato, Observe que nas linhas seguintes pego o campo `e.data`. A variável `error_message` é mais para leitura de humanos. O campo `data` é para exibir na tela exatamente qual o dado está relacionado ao erro.

![image](https://user-images.githubusercontent.com/2096125/193895674-850ffd58-392e-4bdb-8943-cc07dc3c63e3.png)

2022-10-04 18:27 UTC, rafaelpezzuto commented on upload/utils/site_utils.py
> +from packtools.sps.models import (
@robertatakenaka, penso diferente. Posso ter usado o termo site_utils de modo equivocado.

O que fazemos neste módulo é olhar para o `xmltree` e para o `packtools` (models) de modo a obter os campos do `xmltree` que serão usados para comparação (mas não comparamos com opac.article neste ponto). O método retorna um dicionário com os nomes dos campos e os seus respectivos valores. Não há conexão alguma com os dados do opac que justifiquem levá-lo para o módulo `publication`. Talvez deve-se ficar no packtools (um método que extraia todos os conteúdos do XML que serão usados para comparação).

E no publication podemos criar um método que usa esse packtools (data_for_comparison).

2022-10-04 18:32 UTC, rafaelpezzuto commented on upload/templates/modeladmin/upload/package/validation_report/individual_content.html
> +        {% include "wagtailadmin/shared/header_with_locale_selector.html" with title=report_title subtitle=report_subtitle icon='doc-full' %}
@robertatakenaka Isso foi copiado do código original do wagtail. Nesse caso, ele vai procurar por um template específico. O termo que você se refere é algo como {% url '<NOME-DA-URL>' %} ou {% static '<CAMINHO-RELATIVO-DO-ESTÁTICO' %}. Para usar `url` teria de ter uma rota para o template. Acho que não é o caso aqui. Poderíamos tentar static, mas também acho que não é o caso (é um template html).

2022-10-05 18:31 UTC, robertatakenaka approved these changes

2022-10-05 18:32 UTC, merged